version: '3.9'

# Ce fichier est à utiliser avec: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  web:
    environment:
      DEBUG: "True"
      PYTHONUNBUFFERED: "1"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"

  # Volume pour les données de développement
volumes:
  static_volume:
  media_volume:

networks:
  safeplace_network:
