# Generated by Django 6.0.5 on 2026-05-10 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='church', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('spotify', 'Spotify')], max_length=20)),
                ('stream_url', models.URLField(blank=True)),
                ('embed_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('live', 'En Direct'), ('scheduled', 'Programmé'), ('ended', 'Terminé')], default='scheduled', max_length=20)),
                ('viewers_count', models.IntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Live Stream',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('episode_type', models.CharField(choices=[('podcast', 'Podcast'), ('video', 'Vidéo')], default='podcast', max_length=10)),
                ('audio_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=10)),
                ('host', models.CharField(blank=True, default='The SafePlace by K', max_length=100)),
                ('cover_color', models.CharField(default='#00261b', max_length=7)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='podcastSafe.category')),
            ],
            options={
                'verbose_name': 'Épisode',
                'verbose_name_plural': 'Épisodes',
                'ordering': ['-created_at'],
            },
        ),
    ]
