# Generated by Django 6.0.3 on 2026-05-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcastSafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('notify_podcasts', models.BooleanField(default=True, verbose_name='Notifier pour les podcasts')),
                ('notify_live', models.BooleanField(default=True, verbose_name='Notifier pour les lives')),
                ('notify_videos', models.BooleanField(default=False, verbose_name='Notifier pour les vidéos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Abonnement actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-created_at'],
            },
        ),
    ]
