# Generated by Django 4.2.14 on 2026-05-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcastSafe', '0002_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='livestream',
            options={'ordering': ['-created_at'], 'verbose_name': 'Live Stream'},
        ),
    ]
