# Generated by Django 6.0.5 on 2026-05-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcastSafe', '0004_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.AddField(
            model_name='subscription',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL photo de profil'),
        ),
    ]
