"""
Django settings for Safeplace project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-q3=+123_-!0of8m5-!v1tpw!uflyp$$zixw!d^66d6a(hgpa@i')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    host.strip()
    for host in config('ALLOWED_HOSTS', default='localhost,127.0.0.1,testserver,.railway.app').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'podcastSafe',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Safeplace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'podcastSafe' / 'template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'podcastSafe.context_processors.profile_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'Safeplace.wsgi.application'


# ── Base de données ────────────────────────────────────────────────────────────
# PostgreSQL en production, SQLite en développement
if os.getenv('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME':     config('POSTGRES_DB',       default='safeplace_test'),
            'USER':     config('POSTGRES_USER',     default='test'),
            'PASSWORD': config('POSTGRES_PASSWORD', default='test'),
            'HOST':     config('POSTGRES_HOST',     default='localhost'),
            'PORT':     config('POSTGRES_PORT',     default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# ── Validation des mots de passe ───────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ── Internationalisation ───────────────────────────────────────────────────────
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE     = 'UTC'
USE_I18N      = True
USE_TZ        = True


# ── Fichiers statiques ─────────────────────────────────────────────────────────
STATIC_URL        = '/static/'
STATIC_ROOT       = BASE_DIR / 'staticfiles'
STATICFILES_DIRS  = [BASE_DIR / 'static']
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ── URLs principales ───────────────────────────────────────────────────────────
MAIN_SITE_URL    = os.environ.get('MAIN_SITE_URL', 'http://127.0.0.1:8000')
MAIN_API_URL     = os.environ.get('MAIN_API_URL',  'http://127.0.0.1:8000/api/v1/')
from urllib.parse import urlparse

DASHBOARD_API_KEY = os.environ.get('DASHBOARD_API_KEY', 'safeplace_secret_dashboard_key_2026')
DASHBOARD_NETLIFY_URL = os.environ.get('DASHBOARD_NETLIFY_URL', 'https://dashboard-safeplace.netlify.app')
DASHBOARD_URL = os.environ.get('DASHBOARD_URL', DASHBOARD_NETLIFY_URL)

# Normalize origins for CORS (no path allowed)
def get_origin(url):
    parsed = urlparse(url)
    if parsed.scheme and parsed.netloc:
        return f"{parsed.scheme}://{parsed.netloc}"
    return url.rstrip('/')

DASHBOARD_NETLIFY_ORIGIN = get_origin(DASHBOARD_NETLIFY_URL)
DASHBOARD_ORIGIN = get_origin(DASHBOARD_URL)

# URL publique du site (utilisée pour les redirections Wave après paiement)
SITE_URL = config('SITE_URL', default='http://127.0.0.1:8000')

# ── CORS Configuration ───────────────────────────────────────────────────────
CORS_ALLOWED_ORIGINS = [
    DASHBOARD_NETLIFY_ORIGIN,
    DASHBOARD_ORIGIN,
    'http://127.0.0.1:8001',
    'http://localhost:8001',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-api-key',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]


# ── Paiements et dons désactivés ───────────────────────────────────────────
# Plus de configuration Stripe / Wave / paiements directs dans ce projet.


# ── Sécurité des cookies ───────────────────────────────────────────────────────
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE    = not DEBUG


# ── Auth ───────────────────────────────────────────────────────────────────────
LOGIN_URL          = 'admin:login'
LOGIN_REDIRECT_URL = 'home'


# ── Celery ─────────────────────────────────────────────────────────────────────
CELERY_BROKER_URL      = os.environ.get('CELERY_BROKER_URL',    'redis://:redis_password_123@localhost:6379/0')
CELERY_RESULT_BACKEND  = os.environ.get('CELERY_RESULT_BACKEND', 'redis://:redis_password_123@localhost:6379/0')
CELERY_ACCEPT_CONTENT  = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE        = 'UTC'