"""
Django settings for Safeplace project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Application principale URL pour le dashboard
MAIN_SITE_URL = 'http://127.0.0.1:8000'
MAIN_API_URL = 'http://127.0.0.1:8000/api/v1/'
DASHBOARD_API_KEY = 'safeplace_secret_dashboard_key_2026'

# Configuration des dons
DONATION_PAYPAL_URL = 'https://paypal.me/safeplacebyk'
DONATION_KOFI_URL = 'https://ko-fi.com/safeplacebyk'
DONATION_BANK_LABEL = 'The SafePlace by K'
DONATION_BANK_IBAN = 'FR76 1234 5678 9101 1121 3141 516'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q3=+123_-!0of8m5-!v1tpw!uflyp$$zixw!d^66d6a(hgpa@i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'podcastSafe',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Safeplace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'podcastSafe' / 'template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Safeplace.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

from decouple import config

# Use PostgreSQL in production, SQLite in development
if os.getenv('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('POSTGRES_DB', default='safeplace_test'),
            'USER': config('POSTGRES_USER', default='test'),
            'PASSWORD': config('POSTGRES_PASSWORD', default='test'),
            'HOST': config('POSTGRES_HOST', default='localhost'),
            'PORT': config('POSTGRES_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Stripe (optionnel — dons par carte si STRIPE_DONATIONS_ENABLED=true et clés valides)
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_DONATIONS_ENABLED = config('STRIPE_DONATIONS_ENABLED', default='false').lower() in ('1', 'true', 'yes')

# Dons sans frais d’intégration : liens + virement (lu depuis .env / variables d’environnement)
DONATION_PAYPAL_URL = config('DONATION_PAYPAL_URL', default='')
DONATION_KOFI_URL = config('DONATION_KOFI_URL', default='')
DONATION_TIPEEE_URL = config('DONATION_TIPEEE_URL', default='')
DONATION_UTIP_URL = config('DONATION_UTIP_URL', default='')
DONATION_BUYMEACOFFEE_URL = config('DONATION_BUYMEACOFFEE_URL', default='')
DONATION_BANK_IBAN = config('DONATION_BANK_IBAN', default='')
DONATION_BANK_LABEL = config('DONATION_BANK_LABEL', default='The SafePlace by K')
DONATION_NOTIFY_EMAIL = config('DONATION_NOTIFY_EMAIL', default='')

# Session Configuration
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = not DEBUG

# Login URL
LOGIN_URL = 'admin:login'
LOGIN_REDIRECT_URL = 'home'

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://:redis_password_123@localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://:redis_password_123@localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
